### ISSUE TITLE
Error when foreach loop is written with capitalized 'AS' keyword

### ISSUE THREAD

**Issue by yuanzhenbd** [tree-sitter/tree-sitter-php#46] opened 2020-07-05 08:00 UTC
[Agreestore.txt](https://github.com/tree-sitter/tree-sitter-php/files/4874571/Agreestore.txt)

when i analyze the php file above, appear the bug in img:
![image](https://user-images.githubusercontent.com/45750394/86528153-0ee01000-bed8-11ea-9405-0a4d169dcc5e.png)

you can test use the file above, change the file file Extension before use.

**Comment by maxbrunsfeld** [comment] 2020-07-06 16:29
It looks like the parse error is caused by this:

```php
foreach ($rank_list AS $item) {
  // ...
}
```

Currently, the grammar does not recognize the capitalized `AS`. Thank you very much for the report!

**Comment by maxbrunsfeld** [comment] 2020-07-06 19:45
I'm glad you helped us find this; it is fixed on master. Please let us know if you have other unexpected parse errors.

**Closed** 2020-07-06 19:44 UTC
Labels: bug
